### ISSUE TITLE
Setting git user.name

### ISSUE THREAD

**Issue by agiuliano** [parkr/capistrano-slack-notify#16]
I was trying to set the deployer this way:
`set :deployer, `git config user.name``
But it seems slack-notify doesn't read the git config content.
How can I set the git username to the deployer?

**Comment by parkr** [comment]
Are you setting _after_ requiring this library? We set it here: https://github.com/parkr/capistrano-slack-notify/blob/0533e6e9fc880c54f61b0fc7ed327c3dd637362c/lib/capistrano/slack_notify.rb#L105-L107

We use the same method -- are you running Capistrano as your user?
