### ISSUE TITLE
Retrieve revision from remote

### ISSUE THREAD

**Issue by ricoli** [parkr/capistrano-slack-notify#18]
At the moment the revision is retrieved from the local tree, using git rev-parse, which might not be present. I'd propose that the revision would come from a configurable remote, using git ls-remote instead. Thoughts?

**Comment by parkr** [comment]
This is a great idea! In our Capistrano flow, the local rev is used to determine what to deploy. How does it work for you?

**Comment by ricoli** [comment]
It's really for when deploying a certain branch... In order to use git rev-parse, one would have to execute cap from that branch, which is not something required by capistrano, which actually executes ls-remote :)

**Comment by parkr** [comment]
@ricoli Implement it! I'll gladly take a look at a pull request. I still don't quite see where the difference is so I think I just need to see the code to fix that.

**Comment by ricoli** [comment]
Not really sure if this works, my ruby skills are not great... have a look please :)
The difference is that using ls-remote you don't need to have the branch you want to deploy in your local git tree, it just needs to exist on the remote. Of course this would assume that someone actually pushed the branch to the remote... I defaulted the remote to "origin", but the URL would come from Capistrano configuration (:repository).
