### ISSUE TITLE
Not triggered using deploy:migrations

### ISSUE THREAD

**Issue by RyanMacG** [parkr/capistrano-slack-notify#2]
When you run `cap deploy:migrations` no callback for the slack notification is made

**Comment by parkr** [comment]
I'm thinking about removing default hooks and just providing a series of tasks you hook yourself. Would that be cool?

**Comment by RyanMacG** [comment]
:+1: sounds good to me

**Comment by parkr** [comment]
@RyanMacG Just release v1.2.0! Hope it suits you :)
