### ISSUE TITLE
Capistrano dependency outdated

### ISSUE THREAD

**Issue by redrick** [parkr/capistrano-slack-notify#23]
Hi :) 

do you think it is possible to upgrade capistrano dependency to:
`capistrano (~> 3.1)`

all the other cap- gems want it nowadays, I was just wondering since we could really use this gem.

I will try and leave you either PR or comment ;)

THX

**Comment by redrick** [comment]
Ok so I just found myself what it would take to make it >= compatible... 

should I close this issue right away or are you aiming to support it, maybe I can help a bit?

**Comment by parkr** [comment]
Hey @redrick! This gem is for Capistrano 2 specifically, no Capistrano 3. If you can make it compatible, I'd recommend separating out the logic for capistrano 2 and capistrano 3, and requiring the proper file based on `Capistrano::VERSION`. 👍

**Comment by ktaragorn** [comment]
Yes, There are other gems for Cap3, and the main reason for me picking this one is it supports my projects ancient capistrano version. So there is still value to that and I would recommend keeping it.

**Comment by parkr** [comment]
I no longer use this gem actively so I can't be sure it will continue to work as I make more changes. I'm going to keep this to Capistrano 2.x for now. Feel free to fork the project and upgrade as needed!
