### ISSUE TITLE
Add "slack:failed" task

### ISSUE THREAD

**Issue by parkr** [parkr/capistrano-slack-notify#5]
If the deployment fails, we should allow users to notify slack

**Comment by bartzy** [comment]
When/where do I need to run slack:failed? How can I tell when a deployment failed?

**Comment by parkr** [comment]
@Bartzy It will depend. We do `after "deploy:rollback", "slack:failed"`.

**Comment by bartzy** [comment]
But deploy:rollback is executed when any command fails in deploy?

**Comment by parkr** [comment]
> But deploy:rollback is executed when any command fails in deploy?

For us, it is. Capistrano has it built-in, it seems. That said, these sometimes don't work. :/

**Comment by bartzy** [comment]
Got it, thanks!
